### ISSUE TITLE
The login message

### ISSUE THREAD

**Issue by ShengeBelmendo** [WqyJh/sshx#13]
Why is the login message disappeared when using sshx? I use it to login to high performance computers while the login message will be helpful for my operation.

**Comment by WqyJh** [comment]
If you have to see the login message you could use the following command:
```bash
cat /etc/motd
```

**Comment by WqyJh** [comment]
TODO: add the following arguments
```bash
PrintMotd no
PrintLastLog no
```

**Comment by WqyJh** [comment]
> TODO: add the following arguments
> 
> ```shell
> PrintMotd no
> PrintLastLog no
> ```

This two options belong to `sshd_config`, cannot be specified in ssh client.
