### ISSUE TITLE
windows 'no module named termios' Error

### ISSUE THREAD

**Issue by max2max** [WqyJh/sshx#47]
`pip install sshx`
`sshx -h`, then the error occured

**Comment by max2max** [comment]
however, `sshx -h` works in cygwin

**Comment by WqyJh** [comment]
Windows cmd/powershell support has been removed according to #37, since it's hard to implement and buggy. Sorry about that I forgot to update the documentation.

On windows, both wsl or cygwin are good choice for u.

**Comment by max2max** [comment]
Thanks for yuor reply!
