### ISSUE TITLE
May i ask you why don't use stormssh?

### ISSUE THREAD

**Issue by max2max** [WqyJh/sshx#48]
.

**Comment by WqyJh** [comment]
Well, the stormssh does not support cascade jump hosts like:
```bash
sshx connect host1 -v host2,host3
```
which means connecting host1 via host2 while connecting host2 via host3.

This is really convenient for me that I manage serveral machines in an internal network and I need access to them when I was out.

You may suggest teamviewer, but my servers don't have gui environments.

**Comment by max2max** [comment]
So des ne
